name: Test

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

defaults:
  run:
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

        with:
          version: 9.9.0
          run_install: |
            # - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install
          pnpm build

      - name: Install Vitest Browsers
        run: |
          pnpm vitest install chromium --with-deps
          pnpm vitest install firefox --with-deps
          pnpm vitest install webkit --with-deps
          pnpm exec playwright install

      - name: Run Tests
        run: pnpm test:coverage && pnpm test:e2e
      - name: Upload Coverage Reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
